import { KeetaNetErrorBase } from './base';
import { checkableGenerator } from '../utils/helper';
import type { AssertNever } from '../utils/never';

export const ClientErrorCodes = ["BUILDER_AMOUNT_IS_ZERO","BUILDER_CANNOT_READ_BEFORE_RENDER","BUILDER_REQUIRES_PRIVATE_KEY","BUILDER_USER_CLIENT_REQUIRED","PUBLISH_AID_NOT_AVAILABLE","NO_REPS_AVAILABLE","SIGNER_REQUIRES_PRIVATE_KEY","SWAP_INVALID_ACCOUNT_OPTION","SWAP_MISSING_RECEIVE","SWAP_MISSING_SEND","SWAP_OPTIONS_INVALID","SWAP_REQUEST_AMOUNT_MISMATCH","SWAP_REQUEST_TOKEN_MISMATCH","SWAP_SEND_ACCOUNT_MISMATCH","SWAP_SEND_AMOUNT_RECEIVE_EXACT_MISMATCH","SWAP_SEND_AMOUNT_TOO_LOW","SWAP_SEND_RECEIVE_ACCOUNT_MISMATCH","SWAP_SEND_TOKEN_MISMATCH","SYNC_PUBLISH_FAILED"] as const;
export const FullClientErrorCodes: ('CLIENT_BUILDER_AMOUNT_IS_ZERO' | 'CLIENT_BUILDER_CANNOT_READ_BEFORE_RENDER' | 'CLIENT_BUILDER_REQUIRES_PRIVATE_KEY' | 'CLIENT_BUILDER_USER_CLIENT_REQUIRED' | 'CLIENT_PUBLISH_AID_NOT_AVAILABLE' | 'CLIENT_NO_REPS_AVAILABLE' | 'CLIENT_SIGNER_REQUIRES_PRIVATE_KEY' | 'CLIENT_SWAP_INVALID_ACCOUNT_OPTION' | 'CLIENT_SWAP_MISSING_RECEIVE' | 'CLIENT_SWAP_MISSING_SEND' | 'CLIENT_SWAP_OPTIONS_INVALID' | 'CLIENT_SWAP_REQUEST_AMOUNT_MISMATCH' | 'CLIENT_SWAP_REQUEST_TOKEN_MISMATCH' | 'CLIENT_SWAP_SEND_ACCOUNT_MISMATCH' | 'CLIENT_SWAP_SEND_AMOUNT_RECEIVE_EXACT_MISMATCH' | 'CLIENT_SWAP_SEND_AMOUNT_TOO_LOW' | 'CLIENT_SWAP_SEND_RECEIVE_ACCOUNT_MISMATCH' | 'CLIENT_SWAP_SEND_TOKEN_MISMATCH' | 'CLIENT_SYNC_PUBLISH_FAILED')[] = [
	'CLIENT_BUILDER_AMOUNT_IS_ZERO',
	'CLIENT_BUILDER_CANNOT_READ_BEFORE_RENDER',
	'CLIENT_BUILDER_REQUIRES_PRIVATE_KEY',
	'CLIENT_BUILDER_USER_CLIENT_REQUIRED',
	'CLIENT_PUBLISH_AID_NOT_AVAILABLE',
	'CLIENT_NO_REPS_AVAILABLE',
	'CLIENT_SIGNER_REQUIRES_PRIVATE_KEY',
	'CLIENT_SWAP_INVALID_ACCOUNT_OPTION',
	'CLIENT_SWAP_MISSING_RECEIVE',
	'CLIENT_SWAP_MISSING_SEND',
	'CLIENT_SWAP_OPTIONS_INVALID',
	'CLIENT_SWAP_REQUEST_AMOUNT_MISMATCH',
	'CLIENT_SWAP_REQUEST_TOKEN_MISMATCH',
	'CLIENT_SWAP_SEND_ACCOUNT_MISMATCH',
	'CLIENT_SWAP_SEND_AMOUNT_RECEIVE_EXACT_MISMATCH',
	'CLIENT_SWAP_SEND_AMOUNT_TOO_LOW',
	'CLIENT_SWAP_SEND_RECEIVE_ACCOUNT_MISMATCH',
	'CLIENT_SWAP_SEND_TOKEN_MISMATCH',
	'CLIENT_SYNC_PUBLISH_FAILED'
];
export type ClientErrorCode = typeof FullClientErrorCodes[number];

export default class KeetaNetClientError extends KeetaNetErrorBase<ClientErrorCode> {
	static override readonly isInstance: (obj: unknown, strict?: boolean) => obj is KeetaNetClientError =
		checkableGenerator(KeetaNetClientError);

	constructor(code: ClientErrorCode, message: string) {
		super(code, message, { type: 'CLIENT', codes: FullClientErrorCodes });
	}
}

type _AssertMatchesClient = AssertNever<
	| (typeof import('./client') extends typeof import('@keetanetwork/keetanet-client/lib/error/client') ? never : typeof import('./client'))
	| (typeof import('@keetanetwork/keetanet-client/lib/error/client') extends typeof import('./client') ? never : typeof import('@keetanetwork/keetanet-client/lib/error/client'))
>;
